export const categories = [
  { id: "all", label: "All" },
  { id: "electronics", label: "Electronics" },
  { id: "gaming", label: "Gaming" },
  { id: "fashion", label: "Fashion" },
  { id: "home", label: "Home & Living" },
  { id: "beauty", label: "Beauty" },
  { id: "sports", label: "Sports" },
  { id: "books", label: "Books" },
];

export const pools = [
  {
    id: "1",
    title: "iPhone 16 Pro Max 256GB",
    category: "electronics",
    categoryLabel: "Electronics",
    imageUrl: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&q=80&auto=format&fit=crop",
    individualPrice: 1199,
    poolPrice: 949,
    currentParticipants: 67,
    targetParticipants: 100,
    timeLeft: "2d 14h",
    status: "hot",
  },
  {
    id: "2",
    title: "Sony PlayStation 5 Slim",
    category: "gaming",
    categoryLabel: "Gaming",
    imageUrl: "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=600&q=80&auto=format&fit=crop",
    individualPrice: 499,
    poolPrice: 389,
    currentParticipants: 43,
    targetParticipants: 50,
    timeLeft: "6h 30m",
    status: "ending-soon",
  },
  {
    id: "3",
    title: "Nike Air Jordan 1 Retro High",
    category: "fashion",
    categoryLabel: "Fashion",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&q=80&auto=format&fit=crop",
    individualPrice: 180,
    poolPrice: 129,
    currentParticipants: 12,
    targetParticipants: 75,
    timeLeft: "5d 2h",
    status: "new",
  },
  {
    id: "4",
    title: 'Apple MacBook Pro M4 14"',
    category: "electronics",
    categoryLabel: "Electronics",
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&q=80&auto=format&fit=crop",
    individualPrice: 1999,
    poolPrice: 1649,
    currentParticipants: 28,
    targetParticipants: 60,
    timeLeft: "3d 8h",
    status: "hot",
  },
  {
    id: "5",
    title: "Dyson V15 Detect Vacuum",
    category: "home",
    categoryLabel: "Home & Living",
    imageUrl: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&q=80&auto=format&fit=crop",
    individualPrice: 749,
    poolPrice: 579,
    currentParticipants: 55,
    targetParticipants: 80,
    timeLeft: "1d 22h",
    status: "ending-soon",
  },
  {
    id: "6",
    title: 'Samsung 65" QLED 4K Smart TV',
    category: "electronics",
    categoryLabel: "Electronics",
    imageUrl: "https://images.unsplash.com/photo-1461151304267-38535e780c79?w=600&q=80&auto=format&fit=crop",
    individualPrice: 1299,
    poolPrice: 999,
    currentParticipants: 8,
    targetParticipants: 40,
    timeLeft: "6d 10h",
    status: "new",
  },
];

export const stats = {
  activePools: 1240,
  totalSaved: "2.4M",
  members: 48500,
};
