export const categories = [
  { id: "all", label: "All" },
  { id: "electronics", label: "Electronics" },
  { id: "gaming", label: "Gaming" },
  { id: "fashion", label: "Fashion" },
  { id: "home", label: "Home & Living" },
  { id: "beauty", label: "Beauty" },
  { id: "sports", label: "Sports" },
  { id: "books", label: "Books" },
];

export const categoryDetails = [
  {
    id: "electronics",
    label: "Electronics",
    description: "Smartphones, laptops, TVs, and more — the biggest bulk discounts in tech.",
    imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80&auto=format&fit=crop",
    activePools: 342,
    totalSaved: "820K",
  },
  {
    id: "gaming",
    label: "Gaming",
    description: "Consoles, peripherals, and accessories — level up your setup for less.",
    imageUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&q=80&auto=format&fit=crop",
    activePools: 198,
    totalSaved: "410K",
  },
  {
    id: "fashion",
    label: "Fashion",
    description: "Sneakers, apparel, and accessories — premium brands at wholesale prices.",
    imageUrl: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80&auto=format&fit=crop",
    activePools: 275,
    totalSaved: "340K",
  },
  {
    id: "home",
    label: "Home & Living",
    description: "Appliances, furniture, and smart home devices — transform your space for less.",
    imageUrl: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80&auto=format&fit=crop",
    activePools: 156,
    totalSaved: "290K",
  },
  {
    id: "beauty",
    label: "Beauty",
    description: "Skincare, cosmetics, and wellness — luxury beauty at collective prices.",
    imageUrl: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&q=80&auto=format&fit=crop",
    activePools: 112,
    totalSaved: "175K",
  },
  {
    id: "sports",
    label: "Sports",
    description: "Equipment, apparel, and gear — perform your best, spend less.",
    imageUrl: "https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800&q=80&auto=format&fit=crop",
    activePools: 89,
    totalSaved: "130K",
  },
  {
    id: "books",
    label: "Books",
    description: "Textbooks, novels, and professional titles — knowledge shouldn't cost a fortune.",
    imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80&auto=format&fit=crop",
    activePools: 68,
    totalSaved: "55K",
  },
];

export const pools = [
  {
    id: "1",
    title: "iPhone 16 Pro Max 256GB",
    category: "electronics",
    categoryLabel: "Electronics",
    imageUrl: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=800&q=80&auto=format&fit=crop",
    individualPrice: 1199,
    poolPrice: 949,
    currentParticipants: 67,
    targetParticipants: 100,
    timeLeft: "2d 14h",
    status: "hot",
    description:
      "Pool together with 100 buyers to unlock a $250 discount on Apple's flagship iPhone 16 Pro Max. Funds are locked in a smart contract and only released once the best seller bid is selected.",
  },
  {
    id: "2",
    title: "Sony PlayStation 5 Slim",
    category: "gaming",
    categoryLabel: "Gaming",
    imageUrl: "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?w=800&q=80&auto=format&fit=crop",
    individualPrice: 499,
    poolPrice: 389,
    currentParticipants: 43,
    targetParticipants: 50,
    timeLeft: "6h 30m",
    status: "ending-soon",
    description:
      "Only 7 more buyers needed to hit the target for the PS5 Slim pool. Once we reach 50, sellers will compete with their best bulk price — and everyone saves $110.",
  },
  {
    id: "3",
    title: "Nike Air Jordan 1 Retro High",
    category: "fashion",
    categoryLabel: "Fashion",
    imageUrl: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80&auto=format&fit=crop",
    individualPrice: 180,
    poolPrice: 129,
    currentParticipants: 12,
    targetParticipants: 75,
    timeLeft: "5d 2h",
    status: "new",
    description:
      "Fresh pool for the iconic Air Jordan 1 Retro High. We need 75 sneaker buyers to unlock a $51 per-pair discount — that's 28% off retail, on-chain.",
  },
  {
    id: "4",
    title: 'Apple MacBook Pro M4 14"',
    category: "electronics",
    categoryLabel: "Electronics",
    imageUrl: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&q=80&auto=format&fit=crop",
    individualPrice: 1999,
    poolPrice: 1649,
    currentParticipants: 28,
    targetParticipants: 60,
    timeLeft: "3d 8h",
    status: "hot",
    description:
      "The M4 MacBook Pro is a powerhouse. Pool with 60 buyers and save $350 per unit — sellers compete to offer the best bulk pricing once the pool fills.",
  },
  {
    id: "5",
    title: "Dyson V15 Detect Vacuum",
    category: "home",
    categoryLabel: "Home & Living",
    imageUrl: "https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&q=80&auto=format&fit=crop",
    individualPrice: 749,
    poolPrice: 579,
    currentParticipants: 55,
    targetParticipants: 80,
    timeLeft: "1d 22h",
    status: "ending-soon",
    description:
      "Dyson's top-of-the-line vacuum cleaner. 55 buyers in, 25 more to go. Once we hit 80, authorized distributors submit bids — verified unit, full warranty.",
  },
  {
    id: "6",
    title: 'Samsung 65" QLED 4K Smart TV',
    category: "electronics",
    categoryLabel: "Electronics",
    imageUrl: "https://images.unsplash.com/photo-1461151304267-38535e780c79?w=800&q=80&auto=format&fit=crop",
    individualPrice: 1299,
    poolPrice: 999,
    currentParticipants: 8,
    targetParticipants: 40,
    timeLeft: "6d 10h",
    status: "new",
    description:
      "Brand new pool for Samsung's stunning 65-inch QLED TV. We need 40 buyers to invite sellers. Early joiners get the best collective price — $300 off retail.",
  },
];

export const bids = [
  {
    id: "b1",
    poolId: "1",
    seller: "TechDist Inc.",
    location: "Istanbul, Turkey",
    price: 949,
    rating: 4.8,
    reviews: 234,
    delivery: "3–5 days",
    warranty: "1 year Apple warranty",
    verified: true,
    badge: "Best Price",
  },
  {
    id: "b2",
    poolId: "1",
    seller: "GlobalElec Distribution",
    location: "Dubai, UAE",
    price: 965,
    rating: 4.6,
    reviews: 189,
    delivery: "5–7 days",
    warranty: "1 year Apple warranty",
    verified: true,
    badge: null,
  },
  {
    id: "b3",
    poolId: "1",
    seller: "ApplePro Authorized",
    location: "London, UK",
    price: 979,
    rating: 4.9,
    reviews: 512,
    delivery: "2–3 days",
    warranty: "1 year Apple warranty + support",
    verified: true,
    badge: "Top Rated",
  },
];

export const stats = {
  activePools: 1240,
  totalSaved: "2.4M",
  members: 48500,
};
